[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@api3/contracts=lib/contracts/contracts",
    "@api3/airnode-protocol-v1=lib/airnode-protocol-v1",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
